name: Deploy

on:
  push:
    branches: ["main", "config_docker", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add key.pem
        run: echo "${{ secrets.SSH_KEY }}" > "aqa-key.pem"
      - name: Change mode
        run: chmod 400 "aqa-key.pem"
      - name: SSH
        run: |
          ssh -tt -i "aqa-key.pem" -o StrictHostKeyChecking=no ec2-user@aqa-server-ssh.hoanghy.space "
          cd a* && 
          sudo git pull &&
          sudo docker-compose down &&
          sudo docker-compose up --build -d &&
          sudo docker image prune -f &&
          exit
          "